steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/hello-bravo-api'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/hello-bravo-api'

  # Step 3: Deploy the image to Cloud Run with Cloud SQL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hello-bravo-api'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/hello-bravo-api'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '20'
      - '--min-instances'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--add-cloudsql-instances'
      - 'bravocui-site:us-central1:bravocuisite'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,DATABASE_URL=postgresql://your_db_user:your_db_password@/life_tracker?host=/cloudsql/bravocui-site:us-central1:bravocuisite,JWT_SECRET=your-super-secret-jwt-key-change-this-in-production,JWT_ALGORITHM=HS256,JWT_EXPIRE_MINUTES=10080,GOOGLE_CLIENT_ID=772654378329-jq959gvbsuier0oefumlte5ci6hdnsuf.apps.googleusercontent.com,ALLOWED_ORIGINS=https://bravocui.github.io,http://localhost:3000,GCS_BUCKET_NAME=bravocui-site,GCS_PREFIX=prod/'

# Specify the images to be pushed to the registry
images:
  - 'gcr.io/${PROJECT_ID}/hello-bravo-api'

# Optional: Set timeout for the build
timeout: '1200s' 